import type { Stage } from "./stage";
export type Action="aim"|"shoot"|"brace"|"trick";
export const actions:Record<Action,{label:string;keys:string[];instruction:string}>={aim:{label:"Aim",keys:["W","W"],instruction:"Settle on his chest. Hold for power"},shoot:{label:"Quick draw",keys:["W","D"],instruction:"Trace the rising line. Fast and clean"},brace:{label:"Brace",keys:["S","S"],instruction:"Hold inside the white region"},trick:{label:"Trick",keys:["S","A"],instruction:"Follow the line, then reverse"}};
export type Event={time:number;text:string;kind:string;actor:string;action?:Action;quality?:number;point?:number[]};
export type Actor={hp:number;ammo:number;action:Action|null;started:number;commitAt:number;committed:boolean;quality:number;guardUntil:number;buff:number;disrupt:number;hitAt:number;shotAt:number;lean:number;crouch:number};
export type Sample={t:number;x:number;y:number};
export type Frame={t:number;round:number;p:Actor;e:Actor;phase:string;pointer:number[];action:Action|null;start:number};
export type View={phase:string;round:number;hp:number;ammo:number;action:Action|null;partial:string;remaining:number;notice:string;paused:boolean;outcome:string;reason:string;events:Event[];replayProgress:number;replayTime:number};
const clamp=(n:number,a=0,b=1)=>Math.max(a,Math.min(b,n));
const actor=():Actor=>({hp:100,ammo:6,action:null,started:-100,commitAt:0,committed:false,quality:0,guardUntil:-1,buff:0,disrupt:0,hitAt:-100,shotAt:-100,lean:0,crouch:0});
const dist=(a:number[],b:number[])=>Math.hypot(a[0]-b[0],a[1]-b[1]);
function segment(p:number[],a:number[],b:number[]){const dx=b[0]-a[0],dy=b[1]-a[1];const t=clamp(((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1));return {d:dist(p,[a[0]+dx*t,a[1]+dy*t]),t};}
export class Duel{
 stage:Stage;emit:(v:View)=>void;p=actor();e=actor();phase="menu";round=1;t=0;roundStart=0;duration=3;scale=1;partial="";partialAt=0;held="";samples:Sample[]=[];pointer=[.72,.76];keys=new Set<string>();events:Event[]=[];frames:Frame[]=[];history:Action[]=[];paused=false;notice="";noticeUntil=0;outcome="";reason="";raf=0;last=0;lastEmit=0;lastFrame=0;seed=19371;enemyStart=.5;enemyAction:Action="aim";enemyCommit=1.8;replayAt=0;replayEnd=0;deathAt=0;sound=true;audio:AudioContext|null=null;wind:GainNode|null=null;master:GainNode|null=null;lastBeat=0;errors=0;reloadAt=0;reloadTap=-1;shootQuality=0;
 constructor(stage:Stage,emit:(v:View)=>void){this.stage=stage;this.emit=emit;window.addEventListener("keydown",this.down);window.addEventListener("keyup",this.up);window.addEventListener("mousemove",this.move);window.addEventListener("blur",this.blur);document.addEventListener("visibilitychange",this.visibility);this.raf=requestAnimationFrame(this.loop)}
 rand(){this.seed=(Math.imul(1664525,this.seed)+1013904223)>>>0;return this.seed/4294967296}
 audioInit(){if(this.audio)return;try{this.audio=new AudioContext();this.master=this.audio.createGain();this.master.gain.value=this.sound?.45:0;this.master.connect(this.audio.destination);const buffer=this.audio.createBuffer(1,this.audio.sampleRate*2,this.audio.sampleRate),d=buffer.getChannelData(0);let brown=0;for(let i=0;i<d.length;i++){brown=(brown+(Math.random()*2-1)*.018)/1.02;d[i]=brown*3}const src=this.audio.createBufferSource();src.buffer=buffer;src.loop=true;const filter=this.audio.createBiquadFilter();filter.type="lowpass";filter.frequency.value=450;this.wind=this.audio.createGain();this.wind.gain.value=.16;src.connect(filter).connect(this.wind).connect(this.master);src.start()}catch{}}
 tone(freq:number,duration=.15,volume=.1,type:OscillatorType="sine"){if(!this.audio||!this.master)return;const o=this.audio.createOscillator(),g=this.audio.createGain(),t=this.audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*.6,t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(this.master);o.start();o.stop(t+duration)}
 shot(who:string){if(!this.audio||!this.master)return;const b=this.audio.createBuffer(1,this.audio.sampleRate*.2,this.audio.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/(data.length*.12));const src=this.audio.createBufferSource();src.buffer=b;const g=this.audio.createGain();g.gain.value=who==="you"?.7:.35;src.connect(g).connect(this.master);src.start();this.tone(80,.23,.3,"triangle")}
 setSound(v:boolean){this.sound=v;if(this.master&&this.audio)this.master.gain.setTargetAtTime(v?.45:0,this.audio.currentTime,.05)}
 start(mode:string){this.audioInit();this.audio?.resume();this.p=actor();this.e=actor();this.phase="fight";this.round=1;this.t=0;this.scale=mode==="practice"?2:1;this.duration=3*this.scale;this.partial="";this.held="";this.events=[];this.frames=[];this.history=[];this.keys.clear();this.paused=false;this.outcome="";this.reason="";this.lastFrame=0;this.lastBeat=0;this.seed=(Date.now()^Math.floor(Math.random()*1e8))>>>0;this.beginRound();this.say(mode==="practice"?"Slow practice · tap W, then hold W and aim":"The street is yours.",2);this.push()}
 menu(){this.phase="menu";this.paused=false;this.keys.clear();this.held="";this.push()}
 log(text:string,kind="action",who="you",action?:Action,quality?:number){this.events.push({time:this.t,text,kind,actor:who,action,quality});}
 say(text:string,seconds=1){this.notice=text;this.noticeUntil=this.t+seconds}
 pause(v:boolean){if(this.phase==="menu"||this.phase==="end")return;this.paused=v;if(v){this.keys.clear();this.held="";if(this.phase==="fight"&&this.p.action&&!this.p.committed){this.log("Your preparation was cancelled on pause.","cancel");this.p.action=null;this.samples=[]}this.partial=""}this.push()}
 togglePause(){this.pause(!this.paused)}
 blur=()=>{if(this.phase==="fight"||this.phase==="reload")this.pause(true)};
 visibility=()=>{if(document.hidden)this.blur()};
 beginRound(){this.roundStart=this.t;for(const a of [this.p,this.e]){a.action=null;a.committed=false;a.started=-100;a.quality=0;a.disrupt=0;a.guardUntil=-1}this.partial="";this.held="";this.samples=[];this.errors=0;this.pointer=[.72,.76];const last=this.history.slice(-3);let pool:Action[]=["aim","aim","shoot","shoot","brace","trick"];if(last.filter(a=>a==="aim").length>=2)pool=["shoot","shoot","trick"];if(last.filter(a=>a==="shoot").length>=2)pool=["brace","brace","aim"];if(last.filter(a=>a==="brace").length>=2)pool=["trick","aim","trick"];if(this.e.ammo===0)pool=["brace","trick"];this.enemyAction=this.round===11?"shoot":pool[Math.floor(this.rand()*pool.length)];this.enemyStart=(.25+this.rand()*.45)*this.scale;this.enemyCommit=this.enemyStart+({aim:1.05,shoot:.48,brace:.65,trick:.9}[this.enemyAction]+this.rand()*.45)*this.scale;this.log(this.round===11?"Sudden death: one final draw.":`Exchange ${this.round} begins.`,"exchange","both")}
 down=(ev:KeyboardEvent)=>{const k=ev.key.toUpperCase();if(k==="ESCAPE"){ev.preventDefault();this.togglePause();return}if(this.phase!=="fight"&&this.phase!=="reload")return;if(this.paused||ev.ctrlKey||ev.metaKey)return;if(["W","A","S","D","Q","E","C","R"," "].includes(k))ev.preventDefault();if(ev.repeat||this.keys.has(k))return;this.keys.add(k);if(this.phase==="reload"){if(k==="R")this.load();return}if(!["W","A","S","D"].includes(k)||this.p.committed||this.held)return;
 this.events.push({time:this.t,text:`Input ${k}`,kind:"input",actor:"you"});
 if(!this.partial){if(k==="W"||k==="S"){this.partial=k;this.partialAt=this.t;this.tone(240,.04,.03)}else{this.errors++;this.say("Start with W or S.",.5)}this.push();return}
 const combo=this.partial+k;const act=({WW:"aim",WD:"shoot",SS:"brace",SA:"trick"} as Record<string,Action>)[combo];if(!act){this.errors++;this.partial=k==="W"||k==="S"?k:"";this.say("Sequence broken. Reset your hands.",.55);this.push();return}if(this.round===11&&act!=="shoot"){this.partial="";this.say("Final draw: W → D",1);return}if((act==="aim"||act==="shoot")&&this.p.ammo===0){this.partial="";this.say("Empty cylinder. Brace or trick.",.8);this.tone(150,.05,.1);return}this.held=k;this.partial="";this.p.action=act;this.p.started=this.t;this.samples=[{t:this.t,x:this.pointer[0],y:this.pointer[1]}];this.log(`You began ${actions[act].label}.`,"start","you",act);this.push()};
 up=(ev:KeyboardEvent)=>{const k=ev.key.toUpperCase();this.keys.delete(k);if(this.phase!=="fight"||this.paused)return;if(k===this.held){this.held="";this.commit(this.p,this.e,"you",this.grade());this.push()}};
 move=(ev:MouseEvent)=>{const r=this.stage.host.getBoundingClientRect();this.pointer=[clamp((ev.clientX-r.left)/r.width),clamp((ev.clientY-r.top)/r.height)];if(this.phase==="fight"&&!this.paused&&this.held){if(this.samples.length<1000)this.samples.push({t:this.t,x:this.pointer[0],y:this.pointer[1]});if(!this.events.length||this.t-this.events[this.events.length-1].time>.05)this.events.push({time:this.t,text:"Mouse path sample",kind:"path",actor:"you",point:[...this.pointer]})}};
 path(){const end=this.stage.target();return this.p.action==="trick"?[[.72,.76],[.57,.56],[.43,.49]]:[[.72,.76],[.62,.60],end]}
 grade(){const act=this.p.action;if(!act)return .2;const samples=this.samples,hold=(this.t-this.p.started)/this.scale,target=act==="brace"?[.5,.58]:act==="trick"?[.43,.49]:this.stage.target();const alignment=clamp(1-dist(this.pointer,target)/.19);const tail=samples.slice(-10);let velocity=0,acc=0,prev=0;for(let i=1;i<tail.length;i++){const v=dist([tail[i].x,tail[i].y],[tail[i-1].x,tail[i-1].y])/Math.max(.016,tail[i].t-tail[i-1].t);velocity+=v;acc+=Math.abs(v-prev);prev=v}const stability=clamp(1-velocity/Math.max(1,tail.length)*1.8),smooth=clamp(1-acc/Math.max(1,tail.length)*.8);let adherence=alignment,completion=alignment;if(act==="shoot"||act==="trick"){const path=this.path();let total=0;let reached=[false,false,false];for(const s of samples){const p=[s.x,s.y];total+=Math.min(segment(p,path[0],path[1]).d,segment(p,path[1],path[2]).d);path.forEach((v,i)=>{if(dist(p,v)<.12)reached[i]=true})}adherence=clamp(1-total/Math.max(1,samples.length)/.14);completion=reached.filter(Boolean).length/3;if(act==="trick"&&!reached[1])completion*=.4}if(act==="brace"){adherence=samples.filter(s=>dist([s.x,s.y],target)<.065).length/Math.max(1,samples.length)}const ideal=act==="shoot"?.6:act==="trick"?1:act==="brace"?.7:1.35;const timing=clamp(1-Math.abs(hold-ideal)/1.5);const input=clamp(1-this.errors*.2);return clamp(.20+.80*(alignment*.22+adherence*.22+smooth*.09+stability*.09+completion*.14+timing*.14+input*.10))}
 commit(a:Actor,b:Actor,who:string,q:number){if(a.committed||!a.action)return;const action=a.action;const enemy=who==="opponent";a.committed=true;a.commitAt=this.t;a.quality=q;const hold=(this.t-a.started)/this.scale;const grade=q>.88?"Perfect":q>.72?"Sharp":q>.5?"Clean":"Rough";this.log(`${enemy?"Voss":"You"} committed ${actions[action].label} · ${grade.toLowerCase()}.`,"commit",who,action,q);if(!enemy){this.history.push(action);this.say(`${grade} ${actions[action].label.toLowerCase()}`,1)}
 if(action==="brace"){a.guardUntil=this.t+.32*this.scale;this.tone(110,.1,.05,"triangle");return}
 if(action==="trick"){const caught=b.action==="brace"||b.action==="aim"&&!b.committed;const strength=.16+q*.24;b.disrupt=clamp(b.disrupt+(caught?strength:.10));if(caught){b.guardUntil=-1;a.buff=clamp(a.buff+.2);this.log(`${enemy?"Your":"Voss’s"} rhythm broke under the feint.`,"interrupt",who,action);if(b.action==="brace")b.quality*=.4}this.tone(380,.08,.035,"triangle");return}
 if(a.ammo<=0){this.log(`${enemy?"Voss’s":"Your"} cylinder clicked empty.`,"empty",who);return}a.ammo--;a.shotAt=this.t;this.shot(who);
 const charge=action==="aim"?clamp(hold/1.65):0;const targetLean=Math.abs(b.lean);const accuracy=clamp(.38+q*.53+charge*.10+a.buff-a.disrupt-targetLean*.12-b.crouch*.08,.15,.97);a.buff=0;
 const hit=this.rand()<accuracy;this.log(`${enemy?"Voss":"You"} fired${hit?"":" wide"}.`,"shot",who,action,q);if(!hit)return;
 let damage=action==="aim"?15+q*11+charge*14:11+q*13;let blocking=b.action==="brace"&&(this.t-b.started)>.22*this.scale&&(this.t-b.started)<1.25*this.scale&&(!b.committed||this.t<b.guardUntil)&&b.disrupt<.3;
 if(blocking){const bq=enemy?this.grade():b.quality||.6;damage*=1-(.30+bq*.40);b.buff=clamp(b.buff+.17);this.log(`${enemy?"Your":"Voss’s"} brace caught the shot; a counter opening remains.`,"block",who);this.tone(190,.12,.1,"triangle")}
 if(this.round===11)damage=110;b.hp=Math.max(0,b.hp-damage);b.hitAt=this.t;if(!blocking&&b.action&&!b.committed){b.disrupt=clamp(b.disrupt+(action==="shoot"?.22*q:.12));this.log(`${enemy?"Your":"Voss’s"} preparation was disrupted.`,"interrupt",who)}this.log(`${enemy?"You were":"Voss was"} hit${blocking?" through the brace":""}.`,"hit",who,action);if(b.hp<=0){this.finish(enemy?"The street went quiet.":"You outlived the light.",`${enemy?"Voss’s":"Your"} ${actions[action].label.toLowerCase()} landed ${hold.toFixed(2)}s after preparation. ${blocking?"The brace softened the hit, but could not stop it.":b.action&&!b.committed?"It caught an unfinished "+actions[b.action].label.toLowerCase()+".":"The other duelist had no active defensive window."}`);}
 }
 load(){if(this.t-this.reloadTap<.1||this.p.ammo>=6)return;const i=this.p.ammo;const r=this.stage.host.getBoundingClientRect();const el=document.querySelector(".cylinder");if(!el)return;const c=el.getBoundingClientRect();const x=(c.left+c.width*(.5+.35*Math.sin(i*Math.PI/3))-r.left)/r.width,y=(c.top+c.height*(.5-.35*Math.cos(i*Math.PI/3))-r.top)/r.height;if(Math.hypot((this.pointer[0]-x)*r.width,(this.pointer[1]-y)*r.height)<27){this.p.ammo++;this.reloadTap=this.t;this.log(`Chamber ${this.p.ammo} loaded.`,"reload");this.tone(700,.045,.09,"triangle");this.push()}else this.say("Hover the next empty chamber, then tap R.",.6)}
 finish(outcome:string,reason:string){this.outcome=outcome;this.reason=reason;this.phase="death";this.deathAt=this.t;this.held="";this.keys.clear();this.log(this.p.hp<=0?"You fell in the dust.":this.e.hp<=0?"Voss fell in the dust.":"Both guns fell silent.","death","both");this.tone(52,1.2,.18);this.push()}
 replay(){if(!this.frames.length)return;this.phase="replay";this.replayAt=Math.max(0,this.frames[this.frames.length-1].t-7);this.replayEnd=this.frames[this.frames.length-1].t;this.paused=false;this.push()}
 seek(n:number){this.replayAt=this.replayEnd*n/100;this.push()}
 push(){const rt=this.phase==="replay"?this.replayAt:this.t;const events=this.events.filter(e=>e.time<=rt&&e.kind!=="path"&&e.kind!=="input");const displayRound=this.phase==="replay"?(this.frames.findLast(f=>f.t<=this.replayAt)?.round||this.round):this.round;this.emit({phase:this.phase,round:displayRound,hp:this.p.hp,ammo:this.p.ammo,action:this.p.committed?null:this.p.action,partial:this.partial,remaining:this.phase==="reload"?clamp(1-(this.t-this.reloadAt)/3):clamp(1-(this.t-this.roundStart)/this.duration),notice:this.t<this.noticeUntil?this.notice:"",paused:this.paused,outcome:this.outcome,reason:this.reason,events,replayProgress:this.replayEnd?this.replayAt/this.replayEnd*100:0,replayTime:this.replayAt})}
 loop=(now:number)=>{const dt=Math.min(.25,(now-this.last)/1000||0);this.last=now;if(!this.paused&&this.phase!=="menu"&&this.phase!=="end"&&this.phase!=="replay")this.t+=dt;
 if(this.phase==="fight"&&!this.paused){const elapsed=this.t-this.roundStart;this.p.lean+=(Number(this.keys.has("E"))-Number(this.keys.has("Q"))-this.p.lean)*Math.min(1,dt*4);this.p.crouch+=(Number(this.keys.has("C"))-this.p.crouch)*Math.min(1,dt*5);this.e.lean=Math.sin(this.t*1.7)*.25;if(this.partial&&this.t-this.partialAt>1*this.scale){this.partial="";this.errors++;this.say("Sequence expired.",.4)}
 if(!this.e.action&&elapsed>=this.enemyStart){this.e.action=this.enemyAction;this.e.started=this.t;this.e.quality=.48+this.rand()*.38;this.log(`Voss began ${actions[this.enemyAction].label}.`,"start","opponent",this.enemyAction)}
 if(this.e.action&&!this.e.committed&&elapsed>=this.enemyCommit)this.commit(this.e,this.p,"opponent",this.e.quality);
 if(this.phase==="fight"&&elapsed>=this.duration){if(this.held){this.held="";this.commit(this.p,this.e,"you",this.grade()*.82);this.log("The window forced your release.","timeout")}if(this.phase==="fight"){if(this.round===5){this.phase="reload";this.reloadAt=this.t;this.p.ammo=0;this.e.ammo=0;this.partial="";this.log("Restock: both cylinders opened.","reload","both")}else if(this.round===11){this.finish("Neither hand prevailed.","Both final draws missed. The duel ends in a draw.")}else{this.round++;this.beginRound();if(this.round===11)this.say("One last draw. W → D. Any hit is decisive.",3)}}}
 if(this.wind&&this.audio)this.wind.gain.setTargetAtTime(.12+this.round*.013,this.audio.currentTime,.2);if(this.t-this.lastBeat>Math.max(.45,1.5-this.round*.07)){this.lastBeat=this.t;this.tone(this.round>5?73:55,.22,.035,"triangle");if(this.round>7)this.tone(110,.10,.017)}
 }
 if(this.phase==="reload"&&!this.paused){this.e.ammo=Math.min(6,Math.floor((this.t-this.reloadAt)*2.4));if(this.t-this.reloadAt>=3){this.round=6;this.phase="fight";this.beginRound();this.say(this.p.ammo?"The light is leaving.":"Empty. Survive with brace and trick.",1.5)}}
 if(this.phase==="death"&&!this.paused&&this.t-this.deathAt>3){this.replayEnd=this.frames.length?this.frames[this.frames.length-1].t:this.t;this.replay()}
 if(this.phase==="replay"&&!this.paused){this.replayAt+=dt*.5;if(this.replayAt>=this.replayEnd){this.replayAt=this.replayEnd;this.paused=true}}
 if(["fight","reload","death"].includes(this.phase)&&!this.paused&&this.t-this.lastFrame>.033){this.frames.push({t:this.t,round:this.round,p:{...this.p},e:{...this.e},phase:this.phase,pointer:[...this.pointer],action:this.p.action,start:this.p.started});this.lastFrame=this.t}
 let f:Frame={t:this.t,round:this.round,p:this.p,e:this.e,phase:this.phase,pointer:this.pointer,action:this.p.action,start:this.p.started};if(this.phase==="replay"&&this.frames.length){let low=0,high=this.frames.length-1;while(low<high){const mid=Math.ceil((low+high)/2);if(this.frames[mid].t<=this.replayAt)low=mid;else high=mid-1}f=this.frames[low]}
 this.stage.update(f,{menu:this.phase==="menu",replay:this.phase==="replay",paused:this.paused,crouch:this.keys.has("C"),now:now/1000,dt,scale:this.scale,deathAt:this.deathAt,active:this.phase==="fight"&&!this.paused&&!!this.held,samples:this.samples});
 if(now-this.lastEmit>65){this.push();this.lastEmit=now}this.raf=requestAnimationFrame(this.loop)};
 destroy(){cancelAnimationFrame(this.raf);window.removeEventListener("keydown",this.down);window.removeEventListener("keyup",this.up);window.removeEventListener("mousemove",this.move);window.removeEventListener("blur",this.blur);document.removeEventListener("visibilitychange",this.visibility);this.audio?.close()}
}
