"use client";
import { useEffect, useRef, useState } from "react";
import { Crosshair, Volume2, VolumeX, BookOpen, RotateCcw, Play, Pause, ArrowRight } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Slider } from "@/components/ui/slider";
import { Duel, type View, actions } from "./duel";
import { Stage } from "./stage";
export default function Home(){
 const host=useRef<HTMLDivElement>(null), game=useRef<Duel|null>(null), stage=useRef<Stage|null>(null);
 const [view,setView]=useState<View|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(""),[help,setHelp]=useState(false),[sound,setSound]=useState(true),[mode,setMode]=useState("duel");
 useEffect(()=>{let s:Stage;try{s=new Stage(host.current!);stage.current=s;const d=new Duel(s,setView);game.current=d;setReady(true);return()=>{d.destroy();s.destroy()}}catch(e){setError("The 3D scene couldn't start. Enable hardware acceleration or try another browser.");console.error(e)}},[]);
 const active=view?.phase==="fight",replay=view?.phase==="replay",ended=view?.phase==="end",menu=!view||view.phase==="menu";
 const start=()=>{game.current?.start(mode);setHelp(false)};
 return <main className={`game-shell ${active?"in-duel":""}`}>
  <div className="scene" ref={host} aria-label="First-person western duel against a smoke-wreathed gunslinger"/>
  <div className="grain"/><div className="vignette"/>
  <header className="topbar"><div className="wordmark">TEN TILL DARK<span>A DUEL AT SUNDOWN</span></div><div className="utilities"><button aria-label={sound?"Mute sound":"Enable sound"} onClick={()=>{setSound(!sound);game.current?.setSound(!sound)}}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button onClick={()=>{setHelp(true);game.current?.pause(true)}} aria-label="Field guide"><BookOpen size={18}/></button>{!menu&&<button aria-label="Pause duel" onClick={()=>game.current?.togglePause()}><Pause size={18}/></button>}</div></header>
  {menu&&<section className="intro"><p className="eyebrow">DUSTWATER, NEW MEXICO · 1887</p><h1>Ten turns.<br/>One sunset.</h1><p className="intro-copy">Read the hands. Hold your nerve.<br/>Make your move before the light runs out.</p><div className="mode-choice" role="group" aria-label="Game mode"><button className={mode==="duel"?"chosen":""} onClick={()=>setMode("duel")}>THE DUEL <small>3-second exchanges</small></button><button className={mode==="practice"?"chosen":""} onClick={()=>setMode("practice")}>SLOW PRACTICE <small>6-second exchanges</small></button></div><button className="primary start" disabled={!ready} onClick={start}>{ready?"STEP INTO THE STREET":"SETTING THE SCENE…"}<ArrowRight size={18}/></button><button className="text-button" onClick={()=>setHelp(true)}>Read the field guide</button><p className="desktop-note">Keyboard + mouse · Headphones recommended</p>{error&&<p role="alert">{error}</p>}</section>}
  {!menu&&<>
   <div className="round-info"><span>{view?.phase==="reload"?"THE BREATH BETWEEN":replay?"THE LAST WORD":view?.round===11?"ONE LAST DRAW":"SUNSET DUEL"}</span><p>{view?.round===11?"Sudden death":`${String(Math.min(view?.round||1,10)).padStart(2,"0")} / 10`}</p><div className="sunclock">{Array.from({length:10},(_,i)=><i key={i} className={i<(view?.round||1)?"lit":""}/>)}</div></div>
   {view?.notice&&<div className="notice" key={view.notice}>{view.notice}</div>}
   {active&&<><div className="opponent-name">ELIAS “THE PREACHER” VOSS<div className="small-rule"/></div><div className="exchange-meter"><i style={{transform:`scaleX(${view?.remaining||0})`}}/></div></>}
   {(active||view?.phase==="reload")&&<div className="player-status"><div className="health"><span>YOUR CONDITION</span><div><i style={{width:`${view?.hp||0}%`}}/></div><small>{(view?.hp||0)>65?"Steady":(view?.hp||0)>30?"Wounded":"Barely standing"}</small></div><div className="ammo" aria-label={`${view?.ammo} rounds loaded`}>{Array.from({length:6},(_,i)=><i key={i} className={i<(view?.ammo||0)?"loaded":""}/>)}<span>{view?.ammo} / 6</span></div></div>}
   {active&&<div className="action-hud"><div className="execution-hint">{view?.action?`${actions[view.action].instruction} · release ${actions[view.action].keys[0]} to commit`:"HOLD W / D / S / A → GUIDE MOUSE → RELEASE"}</div><div className="actions">{Object.entries(actions).map(([id,a])=><div key={id} className={`action ${view?.action===id?"selected":""}`}><span className="keyseq"><kbd>{a.keys[0]}</kbd></span><span>{a.label}</span></div>)}</div><p className="movement-hint">Q / E lean · C crouch · Esc pause</p></div>}
   {view?.phase==="reload"&&<div className="reload-ui"><p className="eyebrow">FIVE EXCHANGES LEFT</p><h2>Make every chamber count.</h2><p>Move the cursor into each empty chamber. Tap R to load it.</p><div className="cylinder">{Array.from({length:6},(_,i)=><div key={i} className={`chamber ${i<(view?.ammo||0)?"filled":""}`} style={{left:`${50+35*Math.sin(i*Math.PI/3)}%`,top:`${50-35*Math.cos(i*Math.PI/3)}%`}}>{i<(view?.ammo||0)?"●":i+1}</div>)}</div><small>{Math.ceil((view.remaining||0)*3)} seconds · {view.ammo} rounds seated</small></div>}
   {view?.paused&&!replay&&<div className="pause-panel"><p className="eyebrow">HOLD THAT THOUGHT</p><h2>The street can wait.</h2><button className="primary" onClick={()=>game.current?.pause(false)}>RESUME <Play size={16}/></button><button className="text-button" onClick={()=>game.current?.menu()}>Leave duel</button></div>}
   {(ended||replay)&&<div className="results"><p className="eyebrow">{replay?"RECORDED DUEL · HALF SPEED":"DUST SETTLES"}</p><h2>{view?.outcome}</h2><p>{view?.reason}</p><div className="result-buttons"><button className="primary" onClick={start}><RotateCcw size={16}/> ANOTHER SUNSET</button><button className="secondary" onClick={()=>game.current?.replay()}><Play size={16}/> WATCH REPLAY</button></div>{replay&&<div className="replay-bar"><button aria-label={view.paused?"Play replay":"Pause replay"} onClick={()=>game.current?.togglePause()}>{view.paused?<Play size={16}/>:<Pause size={16}/>}</button><Slider aria-label="Replay position" value={[view.replayProgress||0]} min={0} max={100} step={.1} onValueChange={v=>game.current?.seek(v[0])}/><span>{view.replayTime?.toFixed(1)}s</span></div>}<div className="event-log" aria-label="Duel event replay">{view?.events?.slice(-8).map((e,i)=><div key={i}><time>{e.time.toFixed(3).padStart(6,"0")}</time><span>{e.text}</span></div>)}</div></div>}
  </>}
  <Dialog open={help} onOpenChange={o=>{setHelp(o);if(!o)game.current?.pause(false)}}><DialogContent className="field-guide"><DialogTitle className="guide-title">THE FIELD GUIDE</DialogTitle><DialogDescription>Four moves. No guaranteed counters. Execution is your way out.</DialogDescription><img src="/art/dustwater.jpg" alt="Dustwater at sundown, the visual reference for the duel" className="guide-landscape"/><div className="guide-grid"><div><img src="/art/gunslinger.png" alt="Reference silhouette for the smoke-wreathed gunslinger" className="guide-cowboy"/><p className="guide-caption">Watch where the mist thickens: shoulder, wrist and footing.<br/>His health stays hidden.</p></div><div><p><b>Press and hold one move key.</b> The pose and guide remain active while the key is down. Move the mouse, read Voss’s tell, then release to commit.</p><dl><dt>HOLD W · AIM</dt><dd>Move onto his chest and steady the reticle. Holding builds accuracy and power; greed leaves you open.</dd><dt>HOLD D · QUICK DRAW</dt><dd>Trace upward from the low-right holster. A fast, clean release can disrupt a slower shot.</dd><dt>HOLD S · BRACE</dt><dd>Keep the cursor inside the angular region. Protection forms after a short hold, then expires.</dd><dt>HOLD A · TRICK</dt><dd>Trace toward the center, then reverse into the branch. Break his defensive rhythm without spending ammunition.</dd></dl><p>Q / E lean · C crouch · Esc pause. After exchange five, hover empty chambers in order and tap R to reload. Ten exchanges, then one final draw if both survive.</p><p className="muted-copy">Start with slow practice. It doubles execution time without changing the rules. Sound begins when you enter the street.</p></div></div></DialogContent></Dialog>
 </main>
}
