import * as T from "three";
import { SVGRenderer } from "three/examples/jsm/renderers/SVGRenderer.js";
import type { Actor, Frame, Sample } from "./duel";
const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;
type Figure={root:T.Group;body:T.Group;head:T.Group;left:T.Group;right:T.Group;gun:T.Group;leftLeg:T.Group;rightLeg:T.Group;flash:T.Mesh;hat:T.Group;mist:T.Sprite[]};
export class Stage{
 software=false;lastRender=0;host:HTMLDivElement;renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(48,1,.05,180);sun:T.Mesh;light:T.DirectionalLight;ambient:T.HemisphereLight;enemy:Figure;player:Figure;hand:T.Group;handGun:T.Group;handFlash:T.Mesh;enemyFlash:T.PointLight;handLight:T.PointLight;sky:T.Mesh;windmill=new T.Group();dust:T.Points;guide:HTMLCanvasElement;ctx:CanvasRenderingContext2D;resize:ResizeObserver;targetPoint=[.5,.48];skyMaterial:T.ShaderMaterial;reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;lastPhase="";phaseStart=0;width=1;height=1;cameraLean=0;mistMap:T.CanvasTexture;
 constructor(host:HTMLDivElement){this.host=host;try{this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:"high-performance"})}catch{this.software=true;const soft=new SVGRenderer();soft.setPrecision(2);soft.setQuality("low");this.renderer=soft as unknown as T.WebGLRenderer;(this.renderer as any).shadowMap={};(this.renderer as any).setPixelRatio=()=>{};(this.renderer as any).dispose=()=>{}}this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.75));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;host.appendChild(this.renderer.domElement);
 this.guide=document.createElement("canvas");this.guide.style.cssText="position:absolute;inset:0;width:100%;height:100%;pointer-events:none";host.appendChild(this.guide);this.ctx=this.guide.getContext("2d")!;this.mistMap=this.makeMistTexture();
 this.scene.background=new T.Color("#bc7876");this.scene.fog=new T.Fog("#be8c81",23,95);
 this.skyMaterial=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color("#665978")},bottom:{value:new T.Color("#edb382")}},vertexShader:"varying vec3 vPos; void main(){vPos=position; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}",fragmentShader:"varying vec3 vPos;uniform vec3 top;uniform vec3 bottom;void main(){float h=clamp(normalize(vPos).y*2.2,0.0,1.0);gl_FragColor=vec4(mix(bottom,top,pow(h,.75)),1.0);}"});this.sky=new T.Mesh(new T.SphereGeometry(140,24,12),this.skyMaterial);if(!this.software)this.scene.add(this.sky);
 this.ambient=new T.HemisphereLight("#f7cfbd","#514a50",2.25);this.scene.add(this.ambient);this.light=new T.DirectionalLight("#ffd2a0",3.4);this.light.position.set(-12,13,-24);this.light.castShadow=true;this.light.shadow.mapSize.set(2048,2048);Object.assign(this.light.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:1,far:70});this.light.shadow.bias=-.0004;this.scene.add(this.light);this.light.target.position.set(0,0,-5);this.scene.add(this.light.target);
 this.sun=new T.Mesh(new T.SphereGeometry(2.6,32,16),new T.MeshBasicMaterial({color:"#ffddab",fog:false}));this.sun.position.set(-8,13,-75);this.scene.add(this.sun);
 const fill=new T.DirectionalLight("#b0b8ca",.7);fill.position.set(5,6,10);this.scene.add(fill);this.scene.add(new T.AmbientLight("#c3b8ac",this.software?.55:.10));
 this.ground();this.town();this.mountains();this.enemy=this.figure("#373936","#98734c");this.enemy.root.position.set(0,0,-12);this.scene.add(this.enemy.root);host.dataset.characterRendering="procedural-mist";this.player=this.figure("#565d59","#a1794e");this.player.root.position.set(0,0,8);this.player.root.rotation.y=Math.PI;this.player.root.visible=false;this.scene.add(this.player.root);
 this.hand=new T.Group();this.handGun=this.gun();this.handGun.rotation.y=Math.PI;this.handGun.scale.setScalar(.68);this.handGun.position.set(0,0,0);this.hand.add(this.handGun);this.box(this.hand,.14,.17,.25,"#a18566",[0,-.11,.17],[-.25,0,0]);this.box(this.hand,.20,.23,.43,"#555b56",[.025,-.2,.43],[-.28,0,0]);this.box(this.hand,.035,.12,.12,"#967557",[-.075,-.04,.10],[0,0,-.3]);this.camera.add(this.hand);this.scene.add(this.camera);this.handFlash=this.flash();this.handFlash.position.set(0,.05,-.49);this.hand.add(this.handFlash);this.handLight=new T.PointLight("#ffb85a",0,8);this.handLight.position.copy(this.handFlash.position);this.hand.add(this.handLight);this.enemyFlash=new T.PointLight("#ffba64",0,5);this.enemy.root.add(this.enemyFlash);
 const n=this.software?35:230,pos=new Float32Array(n*3);for(let i=0;i<n;i++){pos[i*3]=Math.random()*45-22.5;pos[i*3+1]=Math.random()*4;pos[i*3+2]=Math.random()*70-50}const geo=new T.BufferGeometry();geo.setAttribute("position",new T.BufferAttribute(pos,3));this.dust=new T.Points(geo,new T.PointsMaterial({color:"#efd9b3",size:.035,transparent:true,opacity:.35,depthWrite:false}));this.scene.add(this.dust);
 this.resize=new ResizeObserver(()=>{this.width=host.clientWidth;this.height=host.clientHeight;this.camera.aspect=this.width/this.height;this.camera.updateProjectionMatrix();this.renderer.setSize(this.width,this.height);this.guide.width=this.width*devicePixelRatio;this.guide.height=this.height*devicePixelRatio});this.resize.observe(host);
 }
 mat(color:string){return new T.MeshLambertMaterial({color,flatShading:true})}
 makeMistTexture(){const size=128,c=document.createElement("canvas");c.width=c.height=size;const ctx=c.getContext("2d")!,image=ctx.createImageData(size,size),data=image.data;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const nx=(x+.5)/size*2-1,ny=(y+.5)/size*2-1,r=Math.hypot(nx,ny),angle=Math.atan2(ny,nx),noise=Math.sin(nx*17+Math.sin(ny*9)*2.4)+Math.sin(ny*23-angle*4)+Math.sin((nx+ny)*31)*.45,edge=clamp((1-r)*2.3),alpha=clamp(edge*(.54+noise*.12));const i=(y*size+x)*4;data[i]=data[i+1]=data[i+2]=255;data[i+3]=Math.round(alpha*255)}ctx.putImageData(image,0,0);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;texture.minFilter=T.LinearMipmapLinearFilter;return texture}
 puff(parent:T.Object3D,color:string,x:number,y:number,sx:number,sy:number,opacity:number,z=0){const material=new T.SpriteMaterial({map:this.mistMap,color,transparent:true,opacity,depthWrite:false,alphaTest:.02,fog:true});const sprite=new T.Sprite(material);sprite.position.set(x,y,z);sprite.scale.set(sx,sy,1);sprite.userData.basePosition=sprite.position.clone();sprite.userData.baseScale=new T.Vector2(sx,sy);sprite.userData.baseOpacity=opacity;sprite.userData.mistIndex=sprite.id*.61803398875;parent.add(sprite);return sprite}
 mistCluster(parent:T.Object3D,color:string,points:number[][]){const out:T.Sprite[]=[];for(const p of points){out.push(this.puff(parent,color,p[0],p[1],p[2],p[3],p[4],p[5]||0),this.puff(parent,color,p[0]-p[2]*.14,p[1]+p[3]*.08,p[2]*.82,p[3]*.78,p[4]*.58,(p[5]||0)-.045),this.puff(parent,"#8f9995",p[0]+p[2]*.15,p[1]-p[3]*.05,p[2]*.68,p[3]*.7,p[4]*.28,(p[5]||0)+.045))}return out}
 box(parent:T.Object3D,w:number,h:number,d:number,color:string,p:number[],r=[0,0,0]){const m=new T.Mesh(new T.BoxGeometry(w,h,d),this.mat(color));m.position.set(p[0],p[1],p[2]);m.rotation.set(r[0],r[1],r[2]);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 cyl(parent:T.Object3D,top:number,bottom:number,h:number,color:string,p:number[],segments=8,r=[0,0,0]){const m=new T.Mesh(new T.CylinderGeometry(top,bottom,h,segments),this.mat(color));m.position.set(p[0],p[1],p[2]);m.rotation.set(r[0],r[1],r[2]);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 ground(){const geo=new T.PlaneGeometry(180,180,30,30);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,Math.abs(x)<5&&z>-30&&z<15?-.035:Math.sin(x*.6)*Math.cos(z*.2)*.09-.08)}geo.computeVertexNormals();const mesh=new T.Mesh(geo,this.mat("#bc9971"));mesh.receiveShadow=true;this.scene.add(mesh);for(let i=0;i<55;i++){const x=Math.sin(i*127.1)*21,z=Math.cos(i*37.4)*40-12;if(Math.abs(x)<2)continue;const rock=new T.Mesh(new T.DodecahedronGeometry(.08+(i%4)*.045,0),this.mat(i%2?"#9c856a":"#a78e73"));rock.position.set(x,.04,z);rock.scale.set(1.6,.45,1);rock.castShadow=true;this.scene.add(rock)}for(let side of [-1,1])for(let i=0;i<21;i++){const x=side*(8+(i%5)*2.3),z=-i*3+12;const g=new T.Group();g.position.set(x,0,z);for(let j=0;j<4;j++)this.box(g,.025,.22+(j%3)*.09,.03,"#726d44",[(j-2)*.08,.15,0],[0,j*.7,(j-2)*.3]);this.scene.add(g)}}
 town(){this.building(-8,-4,5,3.8,6,"#777568","TRADING POST",false);this.building(9,-9,6,5.4,7,"#856451","SALOON",true);this.building(-10,-19,6,4.4,7,"#716c68","SHERIFF",true);this.building(12,-27,7,3.5,7,"#867665","STABLES",false);this.building(-11,12,5,3.6,6,"#756c5c","",false);for(const p of [[-5,-1],[5,-7],[-6,-16],[7,-22]]){const [x,z]=p;this.cyl(this.scene,.36,.38,.85,"#75604c",[x,.43,z],10);for(const y of [.2,.65])this.cyl(this.scene,.385,.385,.065,"#454843",[x,y,z],10)}
 const w=new T.Group();w.position.set(15,0,-37);for(const sx of [-1,1])for(const sz of [-1,1])this.box(w,.13,7,.13,"#6a6358",[sx*.65,3.5,sz*.65],[sz*.08,0,-sx*.08]);for(let i=1;i<5;i++){this.box(w,1.3,.07,.08,"#6a6358",[0,i*1.4,.65]);this.box(w,1.3,.07,.08,"#6a6358",[0,i*1.4,-.65])}this.windmill.position.set(0,7,0);for(let i=0;i<10;i++){const a=i*Math.PI/5;this.box(this.windmill,.36,1.4,.055,"#958e76",[Math.sin(a)*1.2,Math.cos(a)*1.2,0],[0,0,-a]);}this.cyl(this.windmill,.18,.18,.25,"#4b4e47",[0,0,0],8,[Math.PI/2,0,0]);w.add(this.windmill);this.scene.add(w);
 for(let z=-34;z<5;z+=6){this.box(this.scene,.15,5.4,.15,"#6d6559",[-16,2.7,z]);this.box(this.scene,1.3,.12,.12,"#6d6559",[-16,5.2,z])}
 }
 sign(text:string){const c=document.createElement("canvas");c.width=512;c.height=100;const ctx=c.getContext("2d")!;ctx.fillStyle="#574b3f";ctx.fillRect(0,0,512,100);ctx.fillStyle="#d6c09c";ctx.font="bold 45px Georgia";ctx.textAlign="center";ctx.fillText(text,256,67);const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;return new T.MeshBasicMaterial({map:tx})}
 building(x:number,z:number,w:number,h:number,d:number,color:string,label:string,upper:boolean){const root=new T.Group();root.position.set(x,0,z);const facing=x<0?Math.PI/2:-Math.PI/2;root.rotation.y=facing;this.box(root,w,h,d,color,[0,h/2,0]);this.box(root,w+.4,.22,d+.5,"#5e5a50",[0,h+.1,0]);this.box(root,w+.35,.62,.17,color,[0,h+.32,d/2]);this.box(root,w+.6,.12,.25,"#59574e",[0,h+.66,d/2]);if(upper){this.box(root,w+.5,.12,1.6,"#82715b",[0,3.05,d/2+.6]);this.box(root,w+.4,.08,.08,"#9c8262",[0,3.85,d/2+1.35]);for(let j=0;j<9;j++)this.box(root,.065,.8,.065,"#8e785a",[-w/2+j*w/8,3.45,d/2+1.35]);for(const side of [-1,1])this.box(root,.12,1.15,.12,"#847057",[side*w*.37,2.52,d/2+.6],[.65,0,0]);}this.box(root,w+.5,.17,2.2,"#9b8767",[0,.09,d/2+.9]);this.box(root,w+.65,.16,2.3,"#676258",[0,2.65,d/2+.9],[.05,0,0]);for(let i=0;i<4;i++)this.box(root,.12,2.6,.12,"#a28a68",[-w/2+.15+i*(w-.3)/3,1.36,d/2+1.8]);for(let y=.35;y<h;y+=.25)this.box(root,w,.015,.02,"#5c584d",[0,y,d/2+.015]);this.box(root,.95,1.9,.06,"#353c39",[0,.99,d/2+.035]);this.box(root,.06,2,.09,"#b09975",[-.51,1,d/2+.09]);this.box(root,.06,2,.09,"#b09975",[.51,1,d/2+.09]);for(const xx of [-w*.32,w*.32]){this.box(root,1.05,1.15,.07,"#bca07b",[xx,1.6,d/2+.06]);this.box(root,.9,1,.08,"#303e41",[xx,1.6,d/2+.11]);this.box(root,.045,1,.08,"#9b8564",[xx,1.6,d/2+.16]);this.box(root,.9,.045,.08,"#9b8564",[xx,1.6,d/2+.16]);if(upper){this.box(root,.85,1,.06,"#b99c76",[xx,h-.85,d/2+.06]);this.box(root,.7,.85,.08,"#354046",[xx,h-.85,d/2+.1])}}if(label){const s=new T.Mesh(new T.PlaneGeometry(w*.8,.65),this.software?this.mat("#5d5143"):this.sign(label));s.position.set(0,upper?3.15:h-.5,d/2+.08);root.add(s)}this.scene.add(root)}
 mountains(){for(let i=0;i<13;i++){const x=(i-6)*11,z=-73-Math.sin(i*4)*11,h=5+(Math.sin(i*17)+1)*5;const g=new T.Mesh(new T.CylinderGeometry(2+(i%3),5+(i%3),h,5,1),this.mat(i%2?"#a46d5d":"#9c6b63"));g.position.set(x,h/2-1,z);g.rotation.y=i;g.scale.z=.7;this.scene.add(g);for(let j=0;j<3;j++){const pillar=new T.Mesh(new T.CylinderGeometry(.6,.95,h*.9,5,2),this.mat(j%2?"#986959":"#b77f64"));pillar.position.set(x-2+j*1.3,h*.4,z+2);pillar.rotation.y=j;this.scene.add(pillar)}}for(let i=0;i<5;i++){this.cyl(this.scene,.22,.3,3,"#6d7757",[-22-i*4,1.5,-15-i*10],6);this.box(this.scene,.65,.18,.22,"#6d7757",[-21.7-i*4,1.9,-15-i*10]);this.cyl(this.scene,.15,.16,.8,"#6d7757",[-21.4-i*4,2.25,-15-i*10],6)}}
 gun(){const g=new T.Group();this.box(g,.12,.12,.55,"#626967",[0,.05,.13]);this.box(g,.065,.055,.5,"#93958b",[0,.125,.12]);this.cyl(g,.083,.083,.25,"#6e7167",[0,.016,-.11],10,[Math.PI/2,0,0]);for(let i=0;i<6;i++){const a=i*Math.PI/3;this.cyl(g,.015,.015,.255,"#383e3b",[Math.sin(a)*.07,.016+Math.cos(a)*.07,-.11],6,[Math.PI/2,0,0])}this.box(g,.08,.23,.12,"#644a36",[0,-.16,-.2],[-.25,0,0]);this.box(g,.10,.08,.18,"#515953",[0,-.04,-.11]);this.box(g,.024,.07,.04,"#aaa897",[0,.15,-.20],[.4,0,0]);this.box(g,.025,.04,.045,"#343d38",[0,.14,.36]);const ring=new T.Mesh(new T.TorusGeometry(.067,.01,4,10),this.mat("#5d625a"));ring.rotation.y=Math.PI/2;ring.position.set(0,-.13,-.04);g.add(ring);const muzzle=new T.Mesh(new T.CircleGeometry(.035,8),this.mat("#22282a"));muzzle.position.set(0,.05,.411);g.add(muzzle);return g}
 flash(){const m=new T.Mesh(new T.IcosahedronGeometry(.22,0),new T.MeshBasicMaterial({color:"#ffe5a3",transparent:true,opacity:.9}));m.scale.set(.55,.55,1.7);m.visible=false;return m}
 figure(coat:string,scarf:string):Figure{const root=new T.Group(),body=new T.Group(),head=new T.Group(),left=new T.Group(),right=new T.Group(),leftLeg=new T.Group(),rightLeg=new T.Group(),mist:T.Sprite[]=[];root.add(body,leftLeg,rightLeg);leftLeg.position.set(-.13,.85,0);rightLeg.position.set(.13,.85,0);mist.push(...this.mistCluster(leftLeg,coat,[[0,-.28,.28,.72,.44,0],[0,-.66,.25,.34,.34,.01]]),...this.mistCluster(rightLeg,coat,[[0,-.28,.28,.72,.44,0],[0,-.66,.25,.34,.34,.01]]));body.position.y=.95;head.position.set(0,.79,0);left.position.set(-.32,.62,0);right.position.set(.32,.62,0);body.add(head,left,right);mist.push(...this.mistCluster(body,coat,[[0,.33,.72,1.08,.5,0],[0,-.08,.78,.64,.42,-.02],[-.18,.48,.45,.62,.26,.04],[.18,.2,.5,.78,.25,.03]]),...this.mistCluster(body,scarf,[[0,.7,.5,.2,.34,.06],[.1,.54,.2,.42,.22,.07]]),...this.mistCluster(head,"#5b625e",[[0,.12,.42,.48,.46,.03]]),...this.mistCluster(left,coat,[[0,-.17,.3,.48,.4,0],[0,-.48,.25,.42,.34,.02]]),...this.mistCluster(right,coat,[[0,-.17,.3,.48,.4,0],[0,-.48,.25,.42,.34,.02]]));const hat=new T.Group();hat.position.set(0,.31,0);head.add(hat);const brim=this.cyl(hat,.36,.34,.045,"#303735",[0,0,0],12);brim.scale.z=.8;this.cyl(hat,.17,.21,.16,"#343b36",[0,.10,0],8);this.cyl(hat,.213,.21,.038,"#675741",[0,.03,0],8);const gun=this.gun();gun.scale.setScalar(.7);gun.position.set(0,-.59,.08);gun.rotation.x=Math.PI/2;right.add(gun);const flash=this.flash();flash.position.set(0,.05,.52);gun.add(flash);return{root,body,head,left,right,gun,leftLeg,rightLeg,flash,hat,mist}}
 pose(f:Figure,a:Actor,t:number,scale:number,menu=false){const injury=1-a.hp/100,age=(t-a.started)/scale,act=a.action;const prep=clamp(age/.9),recovery=a.committed?clamp((t-a.commitAt)/((.55+injury*.35)*scale)):0;const effort=prep*(1-recovery);const hit=Math.exp(-Math.max(0,t-a.hitAt)*12);const breathe=Math.sin(t*(2.5+injury*3))*(.009+injury*.013);f.body.position.y=.95+breathe-a.crouch*.18-(act==="brace"?.13*effort:0);f.body.rotation.z=injury*.07+Math.sin(t*1.3)*.012+a.lean*.13;f.body.rotation.x=injury*.12+hit*.12;f.head.rotation.x=injury*.11+(act==="aim"?.12*effort:0);f.head.rotation.y=Math.sin(t*.4)*.04;f.right.rotation.x=0;f.right.rotation.z=-.06;f.left.rotation.x=injury*.2;f.left.rotation.z=.08;f.gun.rotation.x=Math.PI/2;f.rightLeg.rotation.x=-injury*.08;f.leftLeg.rotation.x=injury*.09;
 if(act==="aim"){f.right.rotation.x=-1.55*effort;f.left.rotation.x=-1.4*effort;f.left.rotation.z=-.32*effort;f.gun.rotation.x=Math.PI/2}
 if(act==="shoot"){f.right.rotation.z=-.25*Math.sin(effort*Math.PI);f.right.rotation.x=-1.45*effort;f.gun.rotation.x=Math.PI/2}
 if(act==="brace"){f.body.rotation.y=.45*effort;f.right.rotation.x=-.8*effort;f.left.rotation.x=-1.1*effort;f.left.rotation.z=-.35*effort}
 if(act==="trick"){const branch=clamp((age-.45)*3);f.right.rotation.x=-1.2*effort*(1-branch*.7);f.body.rotation.y=-.35*effort*branch;f.left.rotation.z=.3*effort;f.head.rotation.y=-.15*effort}
 if(a.committed&&t-a.shotAt<.25){f.right.rotation.x=-1.65+Math.max(0,t-a.shotAt)*1.5;f.gun.rotation.x=Math.PI/2}
 f.root.position.x=a.lean*.32;f.flash.visible=t-a.shotAt>=0&&t-a.shotAt<.09;f.flash.rotation.z=t*34;const sink=a.hp<=0?clamp((t-a.hitAt-.08)/1.45):0,hatFall=a.hp<=0?clamp((t-a.hitAt-.22)/1.2):0;for(const sprite of f.mist){const base=sprite.userData.basePosition as T.Vector3,size=sprite.userData.baseScale as T.Vector2,index=sprite.userData.mistIndex as number,wave=this.reduced?0:Math.sin(t*(.72+index%1.1)+index)*.018;sprite.position.set(base.x+wave,base.y+Math.cos(t*.61+index)*.012,base.z);sprite.scale.set(size.x*(1+sink*.75+wave*2),size.y*(1-sink*.26),1);(sprite.material as T.SpriteMaterial).opacity=(sprite.userData.baseOpacity as number)*(1-sink)*(1-injury*.12)}if(a.hp<=0){f.root.rotation.z=0;f.root.position.y=-1.55*sink;f.hat.position.y=.31+1.55*sink-2.02*hatFall;f.hat.rotation.x=hatFall*1.42;f.hat.rotation.z=hatFall*.38;f.body.rotation.x=0}else{f.root.rotation.z=0;f.root.position.y=0;f.hat.position.set(0,.31,0);f.hat.rotation.set(0,0,0)}
 }
 target(){return [...this.targetPoint]}
 update(f:Frame,o:{menu:boolean;replay:boolean;paused:boolean;crouch:boolean;now:number;dt:number;scale:number;deathAt:number;active:boolean;samples:Sample[]}){const t=o.menu?o.now:f.t;const progress=o.menu?.12:clamp(f.t/(30*o.scale+3));const darkness=clamp((progress-.33)/.67);this.skyMaterial.uniforms.top.value.set("#7e748c").lerp(new T.Color("#151e3b"),darkness);this.skyMaterial.uniforms.bottom.value.set("#eab08a").lerp(new T.Color("#59405f"),darkness);(this.scene.fog as T.Fog).color.set("#c89785").lerp(new T.Color("#353b52"),darkness);this.sun.position.y=lerp(14,-3,progress);(this.sun.material as T.MeshBasicMaterial).color.set("#ffe0af").lerp(new T.Color("#ed8571"),progress);this.light.intensity=lerp(3.2,.18,darkness);this.light.position.y=lerp(13,1,progress);this.ambient.intensity=lerp(2,.7,darkness);this.ambient.color.set("#edc9b3").lerp(new T.Color("#8995ca"),darkness);this.renderer.toneMappingExposure=lerp(1.05,1.2,darkness);this.windmill.rotation.z=t*.19;
 this.pose(this.enemy,f.e,t,o.scale,o.menu);this.pose(this.player,f.p,t,o.scale);this.player.root.position.z=8;if(f.phase==="reload"){this.enemy.right.rotation.x=-.95;this.enemy.left.rotation.x=-1.25;this.enemy.left.rotation.z=-.5;this.enemy.head.rotation.x=.3;this.enemy.right.rotation.z=Math.sin(t*12)*.06;this.enemy.gun.rotation.z=Math.sin(t*7)*.2;}
 const third=(f.phase==="death"||f.p.hp<=0||f.e.hp<=0)&&!o.menu;this.player.root.visible=third;const deathAge=clamp((t-o.deathAt)/2);if(third){this.camera.position.set(lerp(0,5,deathAge),lerp(1.7,3,deathAge),lerp(8,13,deathAge));this.camera.lookAt(0,1,lerp(-12,3,deathAge));this.hand.visible=false}else{this.hand.visible=true;const lean=f.p.lean*.34;this.cameraLean=lerp(this.cameraLean,lean,Math.min(1,o.dt*6));const breath=this.reduced?0:Math.sin(t*2.4)*.008;const hit=clamp(1-(t-f.p.hitAt)/.25);this.camera.position.set(o.menu?-2.5:this.cameraLean,1.73+(-f.p.crouch*.24)+breath-hit*.035,8);this.camera.lookAt(o.menu?-4:0,1.34,-12);this.camera.rotation.z=-this.cameraLean*.07+(this.reduced?0:hit*Math.sin(t*95)*.012)}
 const target=new T.Vector3();this.enemy.body.getWorldPosition(target);target.y+=.35;target.project(this.camera);this.targetPoint=[target.x*.5+.5,-target.y*.5+.5];
 const prep=f.p.action&&!f.p.committed?clamp((t-f.p.started)/.3):0;const shootAge=t-f.p.shotAt,recoil=shootAge>=0?Math.exp(-shootAge*17):0;let hx=.31,hy=-.28,hz=-.85;let rx=-.32,ry=-.15;if(prep){hx=lerp(hx,(f.pointer[0]-.5)*.9,prep*.8);hy=lerp(hy,-.14-(f.pointer[1]-.5)*.7,prep*.8);rx=lerp(rx,0,prep);ry=lerp(ry,0,prep)}if(f.phase==="reload"){hy=-.27;hx=.18;ry=1.1;rx=-.5}this.hand.position.set(hx,hy+recoil*.07,hz+recoil*.12);this.hand.rotation.set(rx-recoil*.20,ry,Math.sin(t*1.7)*.008);this.handFlash.visible=shootAge>=0&&shootAge<.085;this.handLight.intensity=this.handFlash.visible?6:0;this.enemyFlash.position.set(.35,1.35,-.2);this.enemyFlash.intensity=this.enemy.flash.visible?12:0;
 const pos=this.dust.geometry.attributes.position;for(let i=0;i<pos.count;i++){let x=pos.getX(i)+o.dt*(.14+darkness*.2);if(x>24)x=-24;pos.setX(i,x)}pos.needsUpdate=true;(this.dust.material as T.PointsMaterial).opacity=.17+darkness*.13;
 if(!this.software||o.now-this.lastRender>.08){if(this.software){this.scene.background=new T.Color("#ce9d90").lerp(new T.Color("#3b3d59"),darkness)}this.renderer.render(this.scene,this.camera);this.lastRender=o.now}this.drawGuide(f,o.active,o.replay,o.scale,o.samples);}
 drawGuide(f:Frame,active:boolean,replay:boolean,scale:number,samples:Sample[]){const ctx=this.ctx,w=this.width,h=this.height;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,w,h);if(!active&&!replay)return;if(!f.action||f.p.committed)return;const act=f.action,age=(f.t-f.start)/scale,end=this.targetPoint;ctx.strokeStyle="rgba(255,249,229,.85)";ctx.lineWidth=1.3;ctx.shadowColor="#0008";ctx.shadowBlur=3;const path=act==="trick"?[[.72,.76],[.57,.56],[.43,.49]]:[[.72,.76],[.62,.60],end];
 if(act==="aim"){const x=end[0]*w,y=end[1]*h,r=lerp(36,12,clamp(age/1.6));ctx.setLineDash([3,5]);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(x-6,y);ctx.lineTo(x+6,y);ctx.moveTo(x,y-6);ctx.lineTo(x,y+6);ctx.stroke();ctx.font="11px Arial";ctx.fillStyle="#fff4d9";ctx.fillText(age>1.4?"STEADY — RELEASE":"SETTLE",x+r+12,y+4)}
 if(act==="shoot"||act==="trick"){ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(path[0][0]*w,path[0][1]*h);ctx.lineTo(path[1][0]*w,path[1][1]*h);if(act!=="trick"||age>.3)ctx.lineTo(path[2][0]*w,path[2][1]*h);ctx.stroke();ctx.setLineDash([]);for(const [i,p] of path.entries()){if(act==="trick"&&i===2&&age<.3)continue;ctx.beginPath();ctx.arc(p[0]*w,p[1]*h,i===2?12:5,0,Math.PI*2);ctx.stroke()}ctx.font="11px Arial";ctx.fillStyle="#fff4d9";ctx.fillText(act==="trick"&&age>.3?"REVERSE":"DRAW",path[1][0]*w+14,path[1][1]*h)}
 if(act==="brace"){const x=.5*w,y=.58*h,r=42;ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3+Math.PI/6,xx=x+Math.cos(a)*r,yy=y+Math.sin(a)*r;if(!i)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}ctx.closePath();ctx.fillStyle=age>.22&&age<1.25?"#fff8dc12":"#fff8dc04";ctx.fill();ctx.stroke();ctx.font="11px Arial";ctx.fillStyle="#fff4d9";ctx.fillText(age<.22?"FORMING":age<1.25?"HOLD STEADY":"WINDOW CLOSED",x-42,y+r+22)}
 if(samples.length>1&&active){ctx.strokeStyle="#f8e8c655";ctx.lineWidth=1;ctx.beginPath();for(let i=Math.max(0,samples.length-40);i<samples.length;i++){const s=samples[i];if(i===Math.max(0,samples.length-40))ctx.moveTo(s.x*w,s.y*h);else ctx.lineTo(s.x*w,s.y*h)}ctx.stroke()}
 const [px,py]=f.pointer;ctx.strokeStyle="#fffdf2";ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(px*w,py*h,4,0,Math.PI*2);ctx.moveTo(px*w-10,py*h);ctx.lineTo(px*w-6,py*h);ctx.moveTo(px*w+6,py*h);ctx.lineTo(px*w+10,py*h);ctx.stroke();ctx.shadowBlur=0;
 }
 destroy(){this.resize.disconnect();this.scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if((m as T.MeshStandardMaterial).map)(m as T.MeshStandardMaterial).map!.dispose();m.dispose()}}else if(o instanceof T.Sprite){o.material.dispose()}});this.mistMap.dispose();this.renderer.dispose();this.renderer.domElement.remove();this.guide.remove()}
}
